version: '3.8'
services:
    db:
        image: mysql:8.0.25
        restart: always
        environment: 
            MYSQL_DATABASE: peliculas_actores
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes: 
            - .dbdata:/var/lib/mysql
        ports: 
            - 33066:3306